import type { Metadata } from "next";
import "./globals.css";
import {Montserrat} from 'next/font/google';
import Pagina from "@/components/template/Pagina";


export const metadata: Metadata = {
  title: "React & Next",
  description: "Generated by create next app",
};

const font = Montserrat({
 subsets: ['latin'],
  weight:['100','200','300','400','500','600','700','800','900']
}
 
)

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={font.className}>
          <Pagina>
            {children}
          </Pagina>
      </body>
    </html>
  );
}
